/****** Object:  Database [SecondTaskWeatherDataDB]    Script Date: 24-Feb-2023 7:32:35 pm ******/
CREATE DATABASE [SecondTaskWeatherDataDB]  (EDITION = 'GeneralPurpose', SERVICE_OBJECTIVE = 'GP_S_Gen5_1', MAXSIZE = 32 GB) WITH CATALOG_COLLATION = SQL_Latin1_General_CP1_CI_AS;
GO
ALTER DATABASE [SecondTaskWeatherDataDB] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [SecondTaskWeatherDataDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SecondTaskWeatherDataDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SecondTaskWeatherDataDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SecondTaskWeatherDataDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SecondTaskWeatherDataDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [SecondTaskWeatherDataDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SecondTaskWeatherDataDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SecondTaskWeatherDataDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SecondTaskWeatherDataDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SecondTaskWeatherDataDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SecondTaskWeatherDataDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SecondTaskWeatherDataDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SecondTaskWeatherDataDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SecondTaskWeatherDataDB] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO
ALTER DATABASE [SecondTaskWeatherDataDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SecondTaskWeatherDataDB] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [SecondTaskWeatherDataDB] SET  MULTI_USER 
GO
ALTER DATABASE [SecondTaskWeatherDataDB] SET ENCRYPTION ON
GO
ALTER DATABASE [SecondTaskWeatherDataDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [SecondTaskWeatherDataDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 100, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
/*** The scripts of database scoped configurations in Azure should be executed inside the target database connection. ***/
GO
-- ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 8;
GO
/****** Object:  Table [dbo].[Cities]    Script Date: 24-Feb-2023 7:32:35 pm ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cities](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CountryId] [int] NULL,
	[Name] [nvarchar](50) NULL,
	[Code] [nvarchar](10) NULL,
	[Latitude] [decimal](10, 6) NULL,
	[Longitude] [decimal](10, 6) NULL,
 CONSTRAINT [PK_Cities] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Countries]    Script Date: 24-Feb-2023 7:32:35 pm ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Countries](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NULL,
	[Code] [nvarchar](10) NULL,
 CONSTRAINT [PK_Countries] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[WeatherData]    Script Date: 24-Feb-2023 7:32:35 pm ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WeatherData](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CityId] [int] NULL,
	[TemperatureValue] [float] NULL,
	[TemperatureUnit] [nvarchar](50) NULL,
	[WindSpeedValue] [float] NULL,
	[WindSpeedUnit] [nvarchar](50) NULL,
	[Clouds] [nvarchar](50) NULL,
	[LastUpdated] [datetime] NULL,
	[CreatedOn] [datetime] NULL,
 CONSTRAINT [PK_WeatherData] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER DATABASE [SecondTaskWeatherDataDB] SET  READ_WRITE 
GO
